package com.example.finalproject.customer.entity.enums;

public enum JobType {
    OGRENCI,
    UCRETI_OZEL,
    UCRETI_KAMU,
    SERBEST_MESLEK,
    CALISAN_EMEKLI_UCRETI,
    CALISAN_EMEKLI_SERBEST_MESLEK,
    CALISMIYOR,
    YURTDISINDA_CALISAN,
    SIVIL_TOPLUM_KURULUSLARINDA_CALISAN,
    UCRETI_OZERK;
}
